spring.application.name=CourseManagementBackend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Course_db}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vinaya123}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true
server.port=${PORT:8080}