spring.application.name=CourseManagementBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/Course_db
spring.datasource.username=postgres
spring.datasource.password=vinaya123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
server.port=8080